### ISSUE TITLE
Config file missing

### ISSUE THREAD

**Issue by Tom-H3** [mworion/InstallerMW4#3]
Where can I get (or generate) config.cfg?

Tom

**Comment by Tom-H3** [comment]
HI Michael,
Thanks for the info.  I also asked about scripts files and found them in venv. I am making progress but I am not there yet. I posted part of a log file on the 10Micron forum (I could only post part of the log because the whole file exceeded the character limit).

Tom

**Comment by mworion** [comment]
Hi Tom, 
I will check the post in 10micron. Ideally please post the log (drag and drop) to GitHub as there is no limit for it an I could handle it better. the 10micron forum is limited in such things.
I hardly could understand, what you search for. Normally all package data is stored in venv and there should be no need for you as a user to dig into venv to find something you need.
Could you explain better, what you need ?
Michel

**Comment by mworion** [comment]
Closing as the explanation is in 10micron forum
